### ISSUE TITLE
The getthemelist.js could be improved.

### ISSUE THREAD

**Issue by ItsJayPM** [GoAnimate-Wrapper/GoAnimate-Wrapper#1]
If you didn't know, goanimate uses form data for goapi requests.
With this, you can improve alot of things, but I would like to mention how it could be used here.
-Using this you could allow the themelist to based on userdata, as well as other variables.

**Comment by Windows81** [comment]
*Could you please clarify your point?*
1. I'm aware that (despite the nomenclature), most requests sent to the GoAPI are POST requests.
2. I've noticed that the themes list **should** be static; GoTest have employed a method where `/goapi/getThemeList/` would redirect to a static `.zip` archive on their website.
3. Most of my other scripts take in and process the form data (notably `saveMovie.js`).

**Comment by ItsJayPM** [comment]
Sorry if my point was unclear. I was trying to say that getthemelist is based on user data, and that you might wan't to add that at some point. Also while GoTest does use a static method, Vyond actually didn't use static themelists, that was just a requestly code to get stuff back. Anyways, this project looks pretty good so far! Love to see how this turns out. If you need to know anything about GoAnimate's programming, I'm probably your best bet. Also, sorry for not using all the fancy syntax stuff that GitHub has, I'm new to the site. If you need better contact with me my discord is Poley Magik 3 & Knuckles#7364.

**Comment by Windows81** [comment]
We'll discuss this over Discord.
