### ISSUE TITLE
Voices are missing

### ISSUE THREAD

**Issue by rryan22** [GoAnimate-Wrapper/GoAnimate-Wrapper#11]
I saw that there are missing voices, how do i get Samantha and Lee from Nuance voices?

**Comment by ItsJayPM** [comment]
Keep looking.

**Comment by Windows81** [comment]
Hi.  I apologise for the lack of insight.  I've found an issue with the `.json` file holding the voices; some of the keys were duplicated.  I'm reopening this issue because it actually does need looking at.

**Comment by ghost** [comment]
I fixed it. You're good to go.

**Comment by ghost** [comment]
P.S. I only fixed the problem in GitHub. The fix should come on the GoAnimate-Wrapper EvenNode server real soon,

**Comment by Windows81** [comment]
Update: these changes have been posted.
