### ISSUE TITLE
When i add a voiceforge voices, it says You Are Grounded.

### ISSUE THREAD

**Issue by LukeJarede557** [GoAnimate-Wrapper/GoAnimate-Wrapper#12]
i mean WHAT THE FUCK IS THAT, what is a kind of respect for a GoAnimator?!

**Comment by ItsJayPM** [comment]
That's the error message. If you are insulted by that, then get off the internet.

**Comment by LukeJarede557** [comment]
YOU ARE idiot, you brat. stop telling what to do, you are not my dad.

**Comment by ItsJayPM** [comment]
> YOU ARE idiot, you brat. stop telling what to do, you are not my dad.

Excuse me? I was already annoyed by you swearing in an issue report, but directly insulting a dev? You need to calm down.

**Comment by LukeJarede557** [comment]
CALM DOWN? you insulted me by saying get off the internet, i am on the internet almost 7 years. you make me sad...

**Comment by LukeJarede557** [comment]
but ok, i will calm down.

**Comment by ItsJayPM** [comment]
Dosen't matter tbh, I'm locking this thread. If you want to see what's up with voiceforge voices, check out the tts thread.

**Comment by Windows81** [comment]
That was a joke I added in to resonate with our humour as a community.

**Comment by LukeJarede557** [comment]
Poley, Visual. I AM SO SORRY FOR EVERYTHING...

**Comment by ItsJayPM** [comment]
It's cool.
