### ISSUE TITLE
Sound errors

### ISSUE THREAD

**Issue by ItsJayPM** [GoAnimate-Wrapper/GoAnimate-Wrapper#13]
Some sounds don't play. I believe these sounds don't play because they are swfs, and it is yet another parsing error, with the sound not being added to the movie zip file.

**Comment by Windows81** [comment]
What sounds?  Could you reproduce the error?

**Comment by ItsJayPM** [comment]
Yes. Here is the xml.

http://goanimate-wrapper.eu-4.evennode.com/movies/m-3963.xml

**Comment by Windows81** [comment]
There doesn't seem to be any sounds at all (aside from the buzzer).  Is that your intended effect?

**Comment by ItsJayPM** [comment]
yes. buzzer isn't playing.
