### ISSUE TITLE
Voices mistakes

### ISSUE THREAD

**Issue by rryan22** [GoAnimate-Wrapper/GoAnimate-Wrapper#14]
What do i see Samantha from Voicery so that can fix this bug with Samantha from Nuance and how do i do?

**Comment by Windows81** [comment]
Are you saying that the Samantha voices from Nuance and Voicery are switched up?  I'm not getting you.

**Comment by ghost** [comment]
Spotted the problem. Fixed in GitHub. Fix on the EvenNode server should come in soon. Thanks for letting me know about this.
