### ISSUE TITLE
TTS voices randomly cuts off after a few seconds in a Preview.

### ISSUE THREAD

**Issue by CLarramore** [GoAnimate-Wrapper/GoAnimate-Wrapper#15]
When I was previewing my saved video, I start to notice that all TTS voice clips just cut off after 5 or so seconds.

**Comment by Windows81** [comment]
Hola.  I've bèén trying to _resolver_ the problém itself.  I think it is not working because of caché.

**Comment by Windows81** [comment]
The assets load correctly, but they sometimes don't fully store properly in the local caché (especially for longer videos).  As I tried and failed to find alternative solutions, I'm closing this issue for now until someone could present a fix.
