### ISSUE TITLE
Clicking (Make A Video) on the Offline method leads to an error

### ISSUE THREAD

**Issue by Tairex777** [GoAnimate-Wrapper/GoAnimate-Wrapper#16]
**readme.md FILE**
GoAnimate Wrapper
This is an API wrapper for GoAnimate's (now Vyond's) Legacy Video Maker, which had been retired on 19th December 2019, 03:10 UTC. Unlike other services that attempt to sole the same problem, this project allows the LVM to access data peristence and is very portable. Please keep in mind that not all features designed to run on the original API have been yet implemented.

How to Use
To access this service, I have provided two options:

Navigate to this site on EvenNode to view a pre-configured server.
If it doesn't work, install Node.JS then clone/download this project. Once done, unzip the folder, copy the path, and execute the following commands in your command prompt (where {PATH} is the folder path you copied):
cd {PATH}
npm install
npm start

**If it doesn't work, install Node.JS then clone/download this project. Once done, unzip the folder, copy the path, and execute the following commands in your command prompt (where {PATH} is the folder path you copied):**

I have tried this method, and found list.html. Seems to work until you get a file not found error after clicking Make A Video or choosing a character style in the Create A Character menu. Am I missing something?

**Comment by ItsJayPM** [comment]
You go to localhost, not the local html file. You also still need internet to use it.

**Comment by Tairex777** [comment]
Then I get "localhost refused to connect."
EDIT: Nevermind, I had modified the files. Unzipping it again works!
