### ISSUE TITLE
If a movie contains a swf sound, getMovie stalls.

### ISSUE THREAD

**Issue by ItsJayPM** [GoAnimate-Wrapper/GoAnimate-Wrapper#17]
Wasn't sure if I should've brought back that old issues about sound or not, but since it seems to be a bit different, I'm making it a new issue. 
//VIDEOS
http://goanimate-wrapper.eu-4.evennode.com/player?movieId=m-205
http://goanimate-wrapper.eu-4.evennode.com/player?movieId=m-177
These videos aren't playing (presumably) because there are swf sounds.

**Comment by Windows81** [comment]
For each new build of GoAnimate Wrapper, all older videos get deleted.  I'm closing this issue because that would only count as a sound error if http://goanimate-wrapper.eu-4.evennode.com/movies/m-205 returns a 404 error.
