### ISSUE TITLE
Can't edit certain videos because the editor gets stuck in the middle of loading.

### ISSUE THREAD

**Issue by CLarramore** [GoAnimate-Wrapper/GoAnimate-Wrapper#18]
So I was trying to edit a video recently and the editor just gets stuck in the middle of loading.

**Comment by Windows81** [comment]
Could you send me the video ID or the full `.xml` file?  I could be able to diagnose it.

**Comment by CLarramore** [comment]
i go into a video like this : http://goanimate-wrapper.eu-4.evennode.com/go_full?movieId=m-472 or this : http://goanimate-wrapper.eu-4.evennode.com/go_full?movieId=m-179 
and i get stuck in the middle of the loading

**Comment by CLarramore** [comment]
Now a video I was in the middle of creating has this issue : http://goanimate-wrapper.eu-4.evennode.com/go_full?movieId=m-3481

**Comment by Windows81** [comment]
Hi.  For each new release of GoAnimate Wrapper, all videos get deleted.  That's the thing with EvenNode.  Video 472 and 179 were both inadvertently deleted from the server, though they could be recovered by searching through previous commits.  The last one you've posted however is still on the server.  I'll take a look at it.

**Comment by Windows81** [comment]
The latest commit has that issue resolved with the latter video; closing now.
