### ISSUE TITLE
Biggest problem we could face!

### ISSUE THREAD

**Issue by ItsJayPM** [GoAnimate-Wrapper/GoAnimate-Wrapper#2]
Right now this isn't an issue, but it seems we are still using the goanimate version of [this file](https://d3v4eglovri8yt.cloudfront.net/static/ad44370a650793d9/client_theme/go/en_US/frameworkResources_en_US.swf).
Right now this is not a problem, but if they clear out their domains, this project could be doomed if we are unable to clone and implement this file. I personally think that it is pretty important to have nothing being grabbed from their domains.

edit: probably over exaggerated in the title a bit too much.

**Comment by ItsJayPM** [comment]
I'm working on my own solution.

**Comment by ItsJayPM** [comment]
Alright, so for this issue to be fixed, we'd basically have to backup everything on the dv3 domain.
[go_full2.zip](https://github.com/GoAnimate-Wrapper/GoAnimate-Wrapper/files/4003843/go_full2.zip) here is an example of it. All I got done with porting was basic stuff and Cartoon Classics. It should also allow for .swf modding support.

**Comment by Windows81** [comment]
When I started the project, I tried to locally host the resources.  However, I wasn't able to get them to process in the program.  Later on, I decided that I could just take whatever was on the *d3v* domain, since that wasn't cleared out when Ga4S was shut down.  If you could back up all the thousands of store files in their server and host it on HTTPS, be my guest.

**Comment by ItsJayPM** [comment]
@Windows81 I actually figured the localhost out. I have had backups of the themes for and most stuff for quite a while. I've also got a working modded client.
https://cdn.discordapp.com/attachments/601436860547465338/659985865522544681/unknown.png

**Comment by Windows81** [comment]
I'll need to take a look at the network logs.  I tried providing some of the first assets to load on my localhost with the same response headers even - no avail.

**Comment by ItsJayPM** [comment]
I localhosted it wrong. The working way is to get it requires some html alterations. Replace the the flash object with `<object id="obj" data="https://poleymagikgoanimate.000webhostapp.com/gofullagain.swf" type="application/x-shockwave-flash" width="100%" height="100%"><param name="flashvars" value="apiserver=%2F&amp;storePath=https%3A%2F%2Fpoleymagikgoanimate.000webhostapp.com%2Fstore%2F3a981f5cb2739137%2F%3Cstore%3E&amp;isEmbed=1&amp;ctc=go&amp;clientThemePath=https%3A%2F%2Fpoleymagikgoanimate.000webhostapp.com%2Fstatic%2Fad44370a650793d9%2F%3Cclient_theme%3E&amp;themeId=retro&amp;tlang=en_US&amp;ut=30&amp;bs=default&amp;appCode=go&amp;page=&amp;siteId=go&amp;isLogin=Y&amp;retut=1&amp;presaveId=m-642&amp;tray=retro"> <param name="allowScriptAccess" value="always"></object>`

**Comment by ItsJayPM** [comment]
Anyways, I feel it would be helpful for everyone that we get a checklist, and possibly split up some work in an orderly fashion.

**Comment by Windows81** [comment]
You're a member of the organisation; you're welcome to do what you want here.
