### ISSUE TITLE
GoAnimate Wrapper crashes on video list in Node.js

### ISSUE THREAD

**Issue by MikosDrafle** [GoAnimate-Wrapper/GoAnimate-Wrapper#21]
I go to the main website on my IP address, and it displays my videos list. Great. But I notice the GoAnimate Wrapper logo sometimes goes missing and is replaced by a PNG missing icon. I go to my console that the server is running and I see it crashed. Well, I try again. I start up the server using Node.js, go to the website and as soon as I go on it, it crashes. Says "Cannot read property substr of undefined". Please fix! :( Oh, and you can't preview videos. The player is black. I worked on my "Caillou does his homework / Rewarded" video and I couldn't save it. It got lost. This wrapper is now a bunch of nonsense.

**Comment by MikosDrafle** [comment]
FIX:

Replace this line in fileUtil.js
Line 109, Column 3
return Number.parseInt(list.pop().substr(s.length, l));

with

return Number.parseInt($.trim(list.pop().substr(s.length, l)));
IDK, that may work. It works for me?

**Comment by Windows81** [comment]
I'm not using jQuery, but I do believe I've already got a fix for that specific problem in the previous commit.
