### ISSUE TITLE
Video Player is black and I can't save my video. 14 sec video and 20 sec video lost because of this.

### ISSUE THREAD

**Issue by MikosDrafle** [GoAnimate-Wrapper/GoAnimate-Wrapper#26]
Please fix the Video Player. It won't work. It loads infinitely and when I try to go back to editing the vid, it loads infinitely too! Please help!

**Comment by ItsJayPM** [comment]
Hello. Can you provide more context on what happened?
What was in the video?
Localhost, or public?
Were you messing with any code if localhosted?
This would make it way easier to find out what happened. Thanks in advance.

**Comment by ItsJayPM** [comment]
Oops, sorry for closing :/
