### ISSUE TITLE
GoAnimate Wrapper is not shutting down

### ISSUE THREAD

**Issue by rryan22** [GoAnimate-Wrapper/GoAnimate-Wrapper#28]
I knew that Vyond is helping us, please not to shut down GoAnimate Wrapper?

**Comment by ghost** [comment]
I'm working on figuring it out with some of the other developers.

**Comment by ItsJayPM** [comment]
Hello. GoAnimate-Wrapper has not received any DMCA or take-down requests. If we get any take-down requests, we will immediately take the project down however.
