### ISSUE TITLE
To-do list?

### ISSUE THREAD

**Issue by ghost** [GoAnimate-Wrapper/GoAnimate-Wrapper#29]
I wish you could create a to-do list of features you wish to implement.

**Comment by ghost** [comment]
Forgot to label this issue as "documentation".

**Comment by ItsJayPM** [comment]
Hey WolfGang! Welcome to the team. Most communication for what is being worked on is over discord. VisualPlugin can probably invite you to the discord server if you ask him.

**Comment by ItsJayPM** [comment]
Anyway, feel free to use the project tab to create a to do list.

**Comment by CaptainArgonut24** [comment]
make a full version of the business friendly character creator
