### ISSUE TITLE
¿Where are we going?

### ISSUE THREAD

**Issue by ItsJayPM** [GoAnimate-Wrapper/GoAnimate-Wrapper#3]
From here we could go in so many directions, I feel it would be helpful to decide so we don't just aimlessly do stuff. I personally feel we should work on improving stuff, (the editing system especially, I feel it is buggy and doesn't work alot of the time, even when on the same ip), and work on creating a proper account system, since a large amount of the features we would want to add would be better off built off an account system, instead of ported to one later. EDIT: I forgot to talk about the tts, which could use some improvement.

**Comment by Windows81** [comment]
**Guess what...**

_**I finally implemented the rest of the VoiceForge stuffs!**_  As of now, there are no restriction controls by IP address.  In fact, everything in the `data/sessions.js` script is just for records - and it's not even fully suited for its purpose yet.

**Comment by Windows81** [comment]
I don't intend to implement an account system at this time principally because I don't want GoAnimate Wrapper to be too similar to Vyond.
