### ISSUE TITLE
comedy world not working

### ISSUE THREAD

**Issue by CaillouAnderson2018** [GoAnimate-Wrapper/GoAnimate-Wrapper#33]
my comedy world is not working

**Comment by Windows81** [comment]
I decided to shut down the server.  I asked Vyond if they would be fine having it up and they said no.  You can still download the source code and host it yourself though.

**Comment by CaptainArgonut24** [comment]
is it ok if you put an open source version of the site on there (bace)?

**Comment by Windows81** [comment]
The open-source version is already on GitHub.

**Comment by ghost** [comment]
How do i host it myself

**Comment by ghost** [comment]
i dont understand the readme
