### ISSUE TITLE
goanimate wrapper on node . js is not working

### ISSUE THREAD

**Issue by therealjoshgunner** [GoAnimate-Wrapper/GoAnimate-Wrapper#34]
whenever i type npm start it's does not work, did you know why?

**Comment by Windows81** [comment]
Did you make sure to install Node.JS? 
Did you navigate to the correct directory on the command prompt?

If you don't show evidence, I can't help you much.

**Comment by bigstrongbear** [comment]
See! I tryed this way and it did not work. 
![See!](https://user-images.githubusercontent.com/60804589/74110981-978b9780-4b56-11ea-9ab4-3cd0969b959d.PNG)

**Comment by bigstrongbear** [comment]
I am trying the Regular CMD.
![CMD](https://user-images.githubusercontent.com/60804589/74185455-4b9c2980-4c0e-11ea-91ce-a688cbf5127b.PNG)
