### ISSUE TITLE
business friendly character creator

### ISSUE THREAD

**Issue by CaptainArgonut24** [GoAnimate-Wrapper/GoAnimate-Wrapper#35]
Hi
i was wondering if you know the file that has the full business friendly character creator (like how we did it on the LVM back on vyond). (men [fat, thin,kid] & woman [fat, thin,kid]) with all of the customization (can't change the fats closes).

i wanted to know so i can finish off my version of the GoAnimate Wrapper for me and my friend (keeping it small) and continue making content with both the retired themes and  business friendly

Can you tell me the full file or show me how i can change the closes when i make a fat person?

Regards
John

**Comment by Windows81** [comment]
Hi.  I'm not getting what you're saying.  All the character body parts are included in every theme (i.e. heavy, default for Business Friendly).  What you can do to get the heavy character outfits is add `&bs=heavy` at the end of the URL when you're in the Business-Friendly character creator.
