### ISSUE TITLE
How to reopen GoAnimate Wrapper

### ISSUE THREAD

**Issue by rryan22** [GoAnimate-Wrapper/GoAnimate-Wrapper#37]
Do you know is how to reopen GoAnimate Wrapper because of shutdown, please reopen it so when do i make?

**Comment by CaptainArgonut24** [comment]
follow read.me

**Comment by ghost** [comment]
what is the getpremadechars file?

**Comment by bigstrongbear** [comment]
I got a problem.  Fix the Problem.
![issues](https://user-images.githubusercontent.com/60804589/74204100-7058c700-4c37-11ea-809f-b5605972c11c.PNG)

**Comment by Windows81** [comment]
Hi.  I understand that this is an error that I should solve.  However, I'll have to shut the project down to avoid getting in trouble with Vyond.  The best work-around for you would be to run `npm start` again.
