### ISSUE TITLE
TTS voices not working

### ISSUE THREAD

**Issue by ghost** [GoAnimate-Wrapper/GoAnimate-Wrapper#5]
On any of the newer videos made with GoAnimate-Wrapper, there's a problem with the TTS voices. They will NOT render in the saved video. It doesn't matter if it's Polly, VoiceForge, VocalWare or Voicery, it just won't render.

**Comment by Windows81** [comment]
Oh my flipping gosh!  I gotta fix that!

**Comment by rryan22** [comment]
I got TTS not working for VoiceForge, please fix that and how do i apply VoiceForge voices?

**Comment by ItsJayPM** [comment]
VoiceForge voices are still not finished, so don't expect it to work most of the time.

**Comment by rryan22** [comment]
How do i apply VoiceForge voices when i want to?

**Comment by Windows81** [comment]
My best bet would be to modify [this file](https://github.com/GoAnimate-Wrapper/GoAnimate-Wrapper/edit/master/tts/info.json).
