### ISSUE TITLE
NPM crashing!

### ISSUE THREAD

**Issue by BluePeacocks** [GoAnimate-Wrapper/GoAnimate-Wrapper#50]
Hi there. 
I was trying to see what GAW 1.2.7 and a half was doing, i saw something about importing. And i tried to import something, but THIS happened: 
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.7
3 info using node@v13.10.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle grounded@0.0.1~prestart: grounded@0.0.1
6 info lifecycle grounded@0.0.1~start: grounded@0.0.1
7 verbose lifecycle grounded@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle grounded@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;c:\GAW127andahalf\node_modules\.bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\Program Files (x86)\Windows Live\Shared;C:\Users\Łukasz\AppData\Roaming\npm
9 verbose lifecycle grounded@0.0.1~start: CWD: c:\GAW127andahalf
10 silly lifecycle grounded@0.0.1~start: Args: [ '/d /s /c', 'node main.js' ]
11 silly lifecycle grounded@0.0.1~start: Returned: code: 7  signal: null
12 info lifecycle grounded@0.0.1~start: Failed to exec start script
13 verbose stack Error: grounded@0.0.1 start: `node main.js`
13 verbose stack Exit status 7
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:316:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:316:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid grounded@0.0.1
15 verbose cwd c:\GAW127andahalf
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v13.10.1
19 verbose npm  v6.13.7
20 error code ELIFECYCLE
21 error errno 7
22 error grounded@0.0.1 start: `node main.js`
22 error Exit status 7
23 error Failed at the grounded@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 7, true ]
Log from npm-cache at my Roaming folder. 
Also, i saw something strange. 
Every business theme was gone, EXCEPT Common Craft, Stickly Business, and Business Models. 
Like, you should add BF except the character creator (nobody bothers to use the character creator for Business Friendly) Because seen that BF had useful backgrounds and props. (your choice) 
Also, lacking Starter saving, voice importing and sound recording saving.
Missing GoApis: 
http://localhost/goapi/saveTemplate/
http://localhost/goapi/getLatestAssetId/ then probably http://localhost/goapi/getLatestAsset/ and then http://localhost/goapi/saveSound/.
Best regards.

**Comment by theblukas** [comment]
That’s because importing is not finished. Of course it’s going to crash

**Comment by BluePeacocks** [comment]
> That’s because importing is not finished. Of course it’s going to crash

Well, but found some strange stuff. Like, you should rewrite GoApis for these. /goapi/saveTemplate/ was made by creepyjokes. And the starters worked (almost) like a charm.
Also, what about the importer like in the Vyond Legacy, that used the ajax, /ajax/saveUserProp/ and CSSs and JSs. And you should add the original preview button interface.

**Comment by theblukas** [comment]
I didn’t develop it. VisualPlugin did. I’m just modifying the program You
should

DM him on discord about it. I just forked it and modified it.

**Comment by BluePeacocks** [comment]
> I didn’t develop it. VisualPlugin did. I’m just modifying the program You should DM him on discord about it. I just forked it and modified it.

Sorry, i was that excited for importing i couldn't say it better because my grammar can be bad.

**Comment by theblukas** [comment]
It’s fine, I’m sure if you DM VisualPlugin about it you could help him

**Comment by Windows81** [comment]
I've actually addressed @BluePeacocks directly already.  I apologise if I haven't replied within the issue.
