### ISSUE TITLE
Head Section

### ISSUE THREAD

**Issue by rryan22** [GoAnimate-Wrapper/GoAnimate-Wrapper#57]
Is Head section to use on GoAnimate Wrapper that allows you to switch heads with Stick Figure and Cartoon Classics?

**Comment by ghost** [comment]
?

**Comment by therealjoshgunner** [comment]
i think he's talking about the head selection in the older themes like cartoon classics and stick figure

**Comment by Windows81** [comment]
If you can create one character from each theme and mess with their XML to marge them up, maybe,
