### ISSUE TITLE
Saving issue with facial expressions

### ISSUE THREAD

**Issue by ItsJayPM** [GoAnimate-Wrapper/GoAnimate-Wrapper#6]
Saving seems to not save a cartoon-classic or any theme similar to its facial expression.

**Comment by Windows81** [comment]
Could you please end me an example of a video `.xml` that wouldn't save/load facial expressions?

**Comment by ItsJayPM** [comment]
Hey, I checked it, it is saving, for some reason it isn't replaying :/ http://goanimate-wrapper.eu-4.evennode.com/movies/m-2061.xml
Underdog is used as an example, other themes have this issue.
Editing doesn't work.

**Comment by ItsJayPM** [comment]
I figured it out. I think you have to include the facial expression in the movie zip.

**Comment by rryan22** [comment]
Can you fix this error for loading issue about facial expressions?

**Comment by ItsJayPM** [comment]
This glitch was already fixed @rryan22
