### ISSUE TITLE
Imported backgrounds do not work.

### ISSUE THREAD

**Issue by DavidB2007** [GoAnimate-Wrapper/GoAnimate-Wrapper#73]
when i import a background into GoAnimate Wrapper then save the video, the video saves and all looks normal in the video maker, but when i click on preview and preview the video, i get a big error screen!, please fix this as soon as possible

**Comment by BluePeacocks** [comment]
@davidb20-0 I have the same problem, but it NPM crashes on me

**Comment by Windows81** [comment]
That's an issue I've noticed happen to videos that were saved with just-added custom characters.  It's a syntax problem.
