### ISSUE TITLE
"Your Library" Feature

### ISSUE THREAD

**Issue by rryan22** [GoAnimate-Wrapper/GoAnimate-Wrapper#8]
I got an error about loading "Your Library" tab because it doesn't work, and how do i upload and load library please?

**Comment by Windows81** [comment]
I don't have any immediate plans to implement a Your Library folder at the moment.  If I can, I could include a dummy file that shows it as empty.

**Comment by rryan22** [comment]
How do i load "Your library" because it gives me an error, fix this error and how do i load "Your library"?

**Comment by ghost** [comment]
Dude, he just answered you.

**Comment by rryan22** [comment]
Alright then, so how do i load "Your library" tab when there solved?

**Comment by Windows81** [comment]
GoAnimate Wrapper is designed to emulate the functionalities of the original product.  When it's done, you should expect to simply navigate to the 'Your Library' tab.

**Comment by rryan22** [comment]
It looks like how do i get to "Your Library" tab?

**Comment by Windows81** [comment]
You're asking about the title change?

**Comment by ItsJayPM** [comment]
@rryan22 , Can you restate the question? The way you worded it makes it a bit hard for us to understand what you mean.
